-- Active: 1763580614738@@127.0.0.1@5432@mydb
SELECT * FROM users;

DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS invoice_items;
DROP TABLE IF EXISTS invoices;
DROP TABLE IF EXISTS fee_types;
DROP TABLE IF EXISTS house_holds;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS session;

DROP TYPE IF EXISTS user_role;
DROP TABLE IF EXISTS otp_tokens;

ALTER TABLE otp_tokens ALTER COLUMN otp TYPE VARCHAR(255);